/*
const Slides = [
    {
        "id":1,
        "imageURL":require("../images/網站照片/首頁/Cover_photos/cover_photo_1.jpg")
    },
    {
        "id":2,
        "imageURL":require("../images/網站照片/首頁/Cover_photos/cover_photo_2.jpg")
    },
    {
        "id":3,
        "imageURL":require("../images/網站照片/首頁/Cover_photos/cover_photo_3.jpg")
    },
    {
        "id":4,
        "imageURL":require("../images/網站照片/首頁/Cover_photos/cover_photo_4.jpg")
    },
    {
        "id":5,
        "imageURL":require("../images/網站照片/首頁/Cover_photos/cover_photo_5.jpg")
    },
    {
        "id":6,
        "imageURL":require("../images/網站照片/首頁/Cover_photos/cover_photo_6.jpg")
    },
    {
        "id":7,
        "imageURL":require("../images/網站照片/首頁/Cover_photos/cover_photo_7.jpg")
    },
    {
        "id":8,
        "imageURL":require("../images/網站照片/首頁/Cover_photos/cover_photo_8.jpg")
    },
    {
        "id":9,
        "imageURL":require("../images/網站照片/首頁/Cover_photos/cover_photo_9.jpg")
    },
    {
        "id":10,
        "imageURL":require("../images/網站照片/首頁/Cover_photos/cover_photo_10.jpg")
    }
]
export default Slides;
*/